[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
pre_sale_program = "5Y8A7Z6G98zukZcUfWcFfGz29Eh3N8bPPuKXbXuH5534"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/yanmarinich/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
